name: Build TrollRecorder Bypass

on:
  push:
    paths:
      - 'ByPass/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bypass Dylib & Package
        working-directory: ByPass
        run: bash build.sh

      - name: Upload TRApp_ByPass.tipa
        uses: actions/upload-artifact@v4
        with:
          name: TRApp_ByPass.tipa
          path: ByPass/TRApp_ByPass.tipa